### ISSUE TITLE
"tlsv1 alert protocol version" when running the example

### ISSUE THREAD

**Issue by yuefengz** [kelproject/pykube#80] opened 2016-10-11 21:56 UTC
This is the code I run in ipython with python3.5:

``` python
import operator
import pykube
api = pykube.HTTPClient(pykube.KubeConfig.from_file("/Users/yuefengz/.kube/config"))
pods = pykube.Pod.objects(api).filter(namespace="default")
ready_pods = filter(operator.attrgetter("ready"), pods)
```

It throws exception:

```
---------------------------------------------------------------------------
SSLError                                  Traceback (most recent call last)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, **response_kw)
    594                                                   body=body, headers=headers,
--> 595                                                   chunked=chunked)
    596

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    351         try:
--> 352             self._validate_conn(conn)
    353         except (SocketTimeout, BaseSSLError) as e:

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py in _validate_conn(self, conn)
    830         if not getattr(conn, 'sock', None):  # AppEngine might not have  `.sock`
--> 831             conn.connect()
    832

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connection.py in connect(self)
    288                                     server_hostname=hostname,
--> 289                                     ssl_version=resolved_ssl_version)
    290

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/util/ssl_.py in ssl_wrap_socket(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir)
    307     if HAS_SNI:  # Platform-specific: OpenSSL with enabled SNI
--> 308         return context.wrap_socket(sock, server_hostname=server_hostname)
    309

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname)
    376                          server_hostname=server_hostname,
--> 377                          _context=self)
    378

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py in __init__(self, sock, keyfile, certfile, server_side, cert_reqs, ssl_version, ca_certs, do_handshake_on_connect, family, type, proto, fileno, suppress_ragged_eofs, npn_protocols, ciphers, server_hostname, _context)
    751                         raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
--> 752                     self.do_handshake()
    753

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py in do_handshake(self, block)
    987                 self.settimeout(None)
--> 988             self._sslobj.do_handshake()
    989         finally:

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py in do_handshake(self)
    632         """Start the SSL/TLS handshake."""
--> 633         self._sslobj.do_handshake()
    634         if self.context.check_hostname:

SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)

During handling of the above exception, another exception occurred:

SSLError                                  Traceback (most recent call last)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    422                     retries=self.max_retries,
--> 423                     timeout=timeout
    424                 )

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, **response_kw)
    620             clean_exit = False
--> 621             raise SSLError(e)
    622

SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)

During handling of the above exception, another exception occurred:

SSLError                                  Traceback (most recent call last)
<ipython-input-4-93ae656b7489> in <module>()
      3 api = pykube.HTTPClient(pykube.KubeConfig.from_file("/Users/yuefengz/.kube/config"))
      4 pods = pykube.Pod.objects(api).filter(namespace="default")
----> 5 ready_pods = filter(operator.attrgetter("ready"), pods)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pykube/query.py in __iter__(self)
    123
    124     def __iter__(self):
--> 125         return iter(self.query_cache["objects"])
    126
    127     @property

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pykube/query.py in query_cache(self)
    113         if not hasattr(self, "_query_cache"):
    114             cache = {"objects": []}
--> 115             cache["response"] = self.execute().json()
    116             for obj in cache["response"]["items"]:
    117                 cache["objects"].append(self.api_obj_class(self.api, obj))

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pykube/query.py in execute(self)
     97         if self.namespace is not None and self.namespace is not all_:
     98             kwargs["namespace"] = self.namespace
---> 99         r = self.api.get(**kwargs)
    100         r.raise_for_status()
    101         return r

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pykube/http.py in get(self, *args, **kwargs)
    125            - `kwargs`: Keyword arguments
    126         """
--> 127         return self.session.get(*args, **self.get_kwargs(**kwargs))
    128
    129     def options(self, *args, **kwargs):

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py in get(self, url, **kwargs)
    486
    487         kwargs.setdefault('allow_redirects', True)
--> 488         return self.request('GET', url, **kwargs)
    489
    490     def options(self, url, **kwargs):

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    473         }
    474         send_kwargs.update(settings)
--> 475         resp = self.send(prep, **send_kwargs)
    476
    477         return resp

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py in send(self, request, **kwargs)
    594
    595         # Send the request
--> 596         r = adapter.send(request, **kwargs)
    597
    598         # Total elapsed time of the request (approximately)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    495         except (_SSLError, _HTTPError) as e:
    496             if isinstance(e, _SSLError):
--> 497                 raise SSLError(e, request=request)
    498             elif isinstance(e, ReadTimeoutError):
    499                 raise ReadTimeout(e, request=request)

SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)
```

I was using python2.7 but switched to python3.5 because of [issue 29](https://github.com/kelproject/pykube/issues/29).

**Comment by brosner** [comment] 2016-10-21 13:49
I am not sure yet what is causing this, but I suspect it has something to do with how your Python version was built. The paths in the traceback indicate you are using a version of Python downloaded from python.org for macOS. Perhaps that version is using an older openssl version?

I will need to do some tests myself. Could you also indicate which version of Kubernetes you are running?

**Comment by chekolyn** [comment] 2017-02-19 23:20
I've had this issue on macOS too and it's caused by the default OpenSSL (old version) installed in macOS.

``` python
#!/usr/bin/env python
#
#
import platform
import ssl

print "Python info: %s" % (platform.python_version())
print "OpenSSL info: %s" % (ssl.OPENSSL_VERSION)
```

If you have something like:
OpenSSL info: OpenSSL **0.9.8**zh 14 Jan 2016
You will have problems. 

They only way around it it's to brew install openssl and brew install python making sure you point it to the the brewed openssl libraries. That way you can get a newer OpenSSL:
_OpenSSL info: OpenSSL 1.0.2j  26 Sep 2016_  ( this works)

**Comment by brosner** [comment] 2017-02-21 12:37
Thank you for the info @chekolyn. I suspected an older version of OpenSSL was the cause. I am going to close this because there isn't anything we can do other than document this issue.

**Closed by brosner** 2017-02-21 12:37 UTC
